//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AimyRoster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffRoster
    {
        public int Id { get; set; }
        public int StaffId { get; set; }
        public int SiteId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> SalaryCost { get; set; }
        public Nullable<int> RefId { get; set; }
        public string Reference { get; set; }
    
        public virtual Reference Reference1 { get; set; }
        public virtual Site Site { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
